config/routes.rb
# -*- encoding : utf-8 -*-
Olook::Application.routes.draw do
  get "index/index"
  root :to => "home#index"

  match "/bem_vinda", :to => "pages#welcome", :as => "welcome"
  match "/sobre", :to => "pages#about", :as => "about"
  match "/termos", :to => "pages#terms", :as => "terms"
  match "/faq", :to => "pages#faq", :as => "faq"
  match "/privacidade", :to => "pages#privacy", :as => "privacy"
  match "/prazo-de-entrega", :to => "pages#delivery_time", :as => "delivery_time"
  match "/como-funciona", :to => "pages#how_to", :as => "how_to"
  match "/imprensa", :to => "pages#press_release", :as => "press_release"
  match "/lookbooks/lets-party", :to => "lookbooks#lets_party", :as => "lets_party"
  match "/lookbooks/palha", :to => "lookbooks#palha", :as => "palha"
  get   "/contato" => "pages#contact", :as => "contact"
  post  "/contato" => "pages#send_contact", :as => "send_contact"

  get '/pedido/:number/boleto', :to =>'orders#billet', :as => "order_billet"
  get '/pedido/:number/credito', :to =>'orders#credit', :as => "order_credit"
  get '/pedido/:number/debito', :to =>'orders#debit', :as => "order_debit"

  resource :criteo, :only => [:show], :path => 'criteo', :controller => :criteo

  resource :survey, :only => [:new, :create], :path => 'quiz', :controller => :survey
  resources :payments, :path => 'pagamento', :controller => :payments
  resources :credit_cards, :only => [:new, :create], :path => 'credito', :controller => :credit_cards
  resources :debits, :only => [:new, :create], :path => 'debito', :controller => :debits
  resources :billets, :only => [:new, :create], :path => 'boleto', :controller => :billets
  resources :addresses, :path => 'endereco', :controller => :addresses
  resource :cart, :only => [:show, :create, :update, :destroy, :update_status], :path => 'sacola', :controller => :cart do
    collection do
      put "update_bonus" => "cart#update_bonus", :as => "update_bonus"
      put "update_coupon" => "cart#update_coupon", :as => "update_coupon"
      put "update_quantity_product" => "cart#update_quantity_product", :as => "update_quantity_product"
    end
  end
  post "/assign_address", :to => "addresses#assign_address", :as => "assign_address"

  get "/produto/:id" => "product#show", :as => "product"
  get "membro/convite" => "members#invite", :as => 'member_invite'
  get "convite/(:invite_token)" => 'members#accept_invitation', :as => "accept_invitation"
  post "membro/convite_por_email" => 'members#invite_by_email', :as => 'member_invite_by_email'

  get "membro/importar_contatos" => "members#import_contacts", :as => 'member_import_contacts'
  post "membro/importar_contatos" => 'members#show_imported_contacts', :as => 'member_show_imported_contacts'

  post "membro/convidar_contatos" => "members#invite_imported_contacts", :as => 'member_invite_imported_contacts'
  get "membro/convidadas" => "members#invite_list", :as => 'member_invite_list'
  get "membro/vitrine", :to => "members#showroom", :as => "member_showroom"

  get '/conta/pedidos/:number', :controller =>'user/orders', :action => 'show' , :as => "user_order"

  get '/l/:page_url', :controller =>'landing_pages', :action => 'show' , :as => 'landing'

  namespace :user, :path => 'conta' do
    resources :users, :path => 'editar', :only => [:update]
    resources :addresses, :path => 'enderecos'
    resources :orders, :path => 'pedidos', :only => [:index]
    resources :credits, :path => 'creditos' do
      collection do
        post 'creditos/reenviar_convite/:id' => 'credits#resubmit_invite', :as => :resubmit_invite
        post 'creditos/reenviar_todos' => 'credits#resubmit_all_invites', :as => :resubmit_all_invites
      end
    end
  end

  namespace :admin do
    match "/", :to => "index#dashboard"

    resources :products do
      resources :pictures do
        collection do
          get  'multiple_pictures' => 'pictures#new_multiple_pictures', :as => 'new_multiple_pictures'
          post  'multiple_pictures' => 'pictures#create_multiple_pictures', :as => 'create_multiple_pictures'
        end
      end
      resources :details
      resources :variants
      member do
        post 'add_related' => "products#add_related", :as => "add_related"
        delete 'remove_related/:related_product_id' => "products#remove_related", :as => "remove_related"
      end
    end

    resources :users, :except => [:create, :new, :destroy] do
      collection do
        get 'statistics' => 'users#statistics', :as => 'statistics'
        get 'export' => 'users#export', :as => 'export'
      end
    end

    resources :utilities do
      collection do
        post 'restart_resque_workers' => "utilities#restart_resque_workers", :as => "restart_resque_workers"
        post 'invalidates_cdn_content' => "utilities#invalidates_cdn_content", :as => "invalidates_cdn_content"
      end
    end
    resources :shipping_services
    resources :collections
    resources :orders
    resources :coupons, :except => [:destroy]
    resources :landing_pages
  end

  devise_for :admins, :controllers => { :registrations => "registrations", :sessions => "sessions" } do
    post "after_sign_in_path_for", :to => "sessions#after_sign_in_path_for", :as => "after_sign_in_path_for_session"
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations", :sessions => "sessions" } do
    get '/entrar' => 'sessions#new', :as => :new_user_session
    post '/entrar' => 'sessions#create', :as => :user_session
    delete '/logout' => 'sessions#destroy', :as => :destroy_user_session
    get '/users/auth/:provider' => 'omniauth_callbacks#passthru'
    post "after_sign_in_path_for", :to => "sessions#after_sign_in_path_for", :as => "after_sign_in_path_for_session"
  end
end

app/models/landing_page.rb
# -*- encoding : utf-8 -*-

class LandingPage < ActiveRecord::Base
  validates :page_url, :page_title, :presence => true, :uniqueness => true
  validates :page_url, :format => { :with => /^[\w-]+$/ }
  validates :button_url, :format => { :with => /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix }
  mount_uploader :page_image, LandingImageUploader
  mount_uploader :button_image, LandingImageUploader
end

app/controllers/admin/landing_pages_controller.rb
# -*- encoding : utf-8 -*-
class Admin::LandingPagesController < ApplicationController
  before_filter :authenticate_admin!
  layout "admin"
  respond_to :html, :text

  def index
    @landing_pages = LandingPage.all
    respond_with :admin, @landing_pages
  end

  def show
    @landing_page = LandingPage.find(params[:id])
    respond_with :admin, @landing_page
  end

  def new
    @landing_page = LandingPage.new
    respond_with :admin, @landing_page
  end

  def edit
    @landing_page = LandingPage.find(params[:id])
    respond_with :admin, @landing_page
  end

  def create
    @landing_page = LandingPage.new(params[:landing_page])

    if @landing_page.save
      flash[:notice] = 'Landing page was successfully created.'
    end
    respond_with :admin, @landing_page
  end

  def update
    @landing_page = LandingPage.find(params[:id])

    if @landing_page.update_attributes(params[:landing_page])
      flash[:notice] = 'Landing page was successfully updated.'
    end
    respond_with :admin, @landing_page
  end

  def destroy
    @landing_page = LandingPage.find(params[:id])
    @landing_page.destroy
    respond_with :admin, @landing_page
  end

end

app/controllers/landing_pages_controller.rb
# -*- encoding : utf-8 -*-
class LandingPagesController < ApplicationController
  def show
    @landing_page = LandingPage.find_by_page_url(params[:page_url])
  end
end

app/views/admin/landing_pages/_form.html.erb
<%= form_for([:admin,@landing_page]) do |f| %>
  <% if @landing_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@landing_page.errors.count, "error") %> prohibited this landing page from being saved:</h2>

      <ul>
      <% @landing_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :page_title %><br />
    <%= f.text_field :page_title %>
  </div>
  <div class="field">
    <%= f.label :page_url %><br />
    <%= f.text_field :page_url %>
  </div>
  <div class="field">
    <%= f.label :page_image %><br />
    <%= f.file_field :page_image %>
  </div>
  <div class="field">
    <%= f.label :button_image %><br />
    <%= f.file_field :button_image %>
  </div>
  <div class="field">
    <%= f.label :button_url %><br />
    <%= f.text_field :button_url %>
  </div>
  <div class="field">
    <%= f.label :enabled %><br />
    <%= f.check_box :enabled %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/landing_pages/edit.html.erb
<h2>Editing landing page</h2>

<div class="inner">
  <%= render 'form' %>

  <%= link_to 'Show', admin_landing_page_path(@landing_page) %> |
  <%= link_to 'Back', admin_landing_pages_path %>
</div>

app/views/admin/landing_pages/index.html.erb
<h2>Listing Landing pages</h2>

<div class="inner">
  <table>
    <tr>
      <th>Title</th>
      <th>URL</th>
      <th>Enabled</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @landing_pages.each do |page| %>
    <tr>
      <td><%= page.page_title %></td>
      <td><%= page.page_url %></td>
      <td><%= page.enabled %></td>
      <td><%= link_to 'Show', admin_landing_page_path(page) %></td>
      <td><%= link_to 'Edit', edit_admin_landing_page_path(page) %></td>
      <td><%= link_to 'Destroy', admin_landing_page_path(page), confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  </table>

  <br />

  <%= link_to 'New Landing page', new_admin_landing_page_path %>
</div>

app/views/admin/landing_pages/new.html.erb
<h2>New Landing page</h2>

<div class="inner">
  <%= render 'form' %>

  <%= link_to 'Back', admin_landing_pages_path %>
</div>

app/views/admin/landing_pages/show.html.erb
<div class="inner">
  <p id="notice"><%= notice %></p>

  <p>
    <b>Title:</b>
    <%= @landing_page.page_title %>
  </p>

  <p>
    <b>URL:</b>
    <%= @landing_page.page_url %>
  </p>

  <p>
    <b>Image:</b>
    <%= image_tag @landing_page.page_image.thumb.try(:url) %>
  </p>

  <p>
    <b>Button url:</b>
    <%= @landing_page.button_url %>
  </p>

  <p>
    <b>Button alt:</b>
    <%= @landing_page.button_url %>
  </p>

  <p>
    <b>Button image:</b>
    <%= @landing_page.button_image %>
  </p>

  <p>
    <b>Enabled:</b>
    <%= @landing_page.enabled %>
  </p>

  <p>
    <b>Show header:</b>
    <%= @landing_page.show_header %>
  </p>

  <p>
    <b>Show footer:</b>
    <%= @landing_page.show_footer %>
  </p>

  <%= link_to 'Edit', edit_admin_landing_page_path(@anding_page) %> |
  <%= link_to 'Back', admin_landing_pages_path %>
</div>