config/routes.rb
# -*- encoding : utf-8 -*-
Olook::Application.routes.draw do
  get "index/index"
  root :to => "home#index"

  match "/bem_vinda", :to => "pages#welcome", :as => "welcome"
  match "/sobre", :to => "pages#about", :as => "about"
  match "/termos", :to => "pages#terms", :as => "terms"
  match "/faq", :to => "pages#faq", :as => "faq"
  match "/privacidade", :to => "pages#privacy", :as => "privacy"
  match "/prazo-de-entrega", :to => "pages#delivery_time", :as => "delivery_time"
  match "/como-funciona", :to => "pages#how_to", :as => "how_to"
  match "/imprensa", :to => "pages#press_release", :as => "press_release"
  match "/lookbooks/lets-party", :to => "lookbooks#lets_party", :as => "lets_party"
  match "/lookbooks/palha", :to => "lookbooks#palha", :as => "palha"
  get   "/contato" => "pages#contact", :as => "contact"
  post  "/contato" => "pages#send_contact", :as => "send_contact"

  get '/pedido/:number/boleto', :to =>'orders#billet', :as => "order_billet"
  get '/pedido/:number/credito', :to =>'orders#credit', :as => "order_credit"
  get '/pedido/:number/debito', :to =>'orders#debit', :as => "order_debit"

  resource :criteo, :only => [:show], :path => 'criteo', :controller => :criteo

  resource :survey, :only => [:new, :create], :path => 'quiz', :controller => :survey
  resources :payments, :path => 'pagamento', :controller => :payments
  resources :credit_cards, :only => [:new, :create], :path => 'credito', :controller => :credit_cards
  resources :debits, :only => [:new, :create], :path => 'debito', :controller => :debits
  resources :billets, :only => [:new, :create], :path => 'boleto', :controller => :billets
  resources :addresses, :path => 'endereco', :controller => :addresses
  resource :cart, :only => [:show, :create, :update, :destroy, :update_status], :path => 'sacola', :controller => :cart do
    collection do
      put "update_bonus" => "cart#update_bonus", :as => "update_bonus"
      put "update_coupon" => "cart#update_coupon", :as => "update_coupon"
      put "update_quantity_product" => "cart#update_quantity_product", :as => "update_quantity_product"
    end
  end
  post "/assign_address", :to => "addresses#assign_address", :as => "assign_address"

  get "/produto/:id" => "product#show", :as => "product"
  get "membro/convite" => "members#invite", :as => 'member_invite'
  get "convite/(:invite_token)" => 'members#accept_invitation', :as => "accept_invitation"
  post "membro/convite_por_email" => 'members#invite_by_email', :as => 'member_invite_by_email'

  get "membro/importar_contatos" => "members#import_contacts", :as => 'member_import_contacts'
  post "membro/importar_contatos" => 'members#show_imported_contacts', :as => 'member_show_imported_contacts'

  post "membro/convidar_contatos" => "members#invite_imported_contacts", :as => 'member_invite_imported_contacts'
  get "membro/convidadas" => "members#invite_list", :as => 'member_invite_list'
  get "membro/vitrine", :to => "members#showroom", :as => "member_showroom"

  get '/conta/pedidos/:number', :controller =>'user/orders', :action => 'show' , :as => "user_order"

  get '/l/:page_url', :controller =>'landing_pages', :action => 'show' , :as => 'landing'

  namespace :user, :path => 'conta' do
    resources :users, :path => 'editar', :only => [:update]
    resources :addresses, :path => 'enderecos'
    resources :orders, :path => 'pedidos', :only => [:index]
    resources :credits, :path => 'creditos' do
      collection do
        post 'creditos/reenviar_convite/:id' => 'credits#resubmit_invite', :as => :resubmit_invite
        post 'creditos/reenviar_todos' => 'credits#resubmit_all_invites', :as => :resubmit_all_invites
      end
    end
  end

  namespace :admin do
    match "/", :to => "index#dashboard"

    resources :products do
      resources :pictures do
        collection do
          get  'multiple_pictures' => 'pictures#new_multiple_pictures', :as => 'new_multiple_pictures'
          post  'multiple_pictures' => 'pictures#create_multiple_pictures', :as => 'create_multiple_pictures'
        end
      end
      resources :details
      resources :variants
      member do
        post 'add_related' => "products#add_related", :as => "add_related"
        delete 'remove_related/:related_product_id' => "products#remove_related", :as => "remove_related"
      end
    end

    resources :users, :except => [:create, :new, :destroy] do
      collection do
        get 'statistics' => 'users#statistics', :as => 'statistics'
        get 'export' => 'users#export', :as => 'export'
      end
    end

    resources :utilities do
      collection do
        post 'restart_resque_workers' => "utilities#restart_resque_workers", :as => "restart_resque_workers"
        post 'invalidates_cdn_content' => "utilities#invalidates_cdn_content", :as => "invalidates_cdn_content"
      end
    end
    resources :shipping_services
    resources :collections
    resources :orders
    resources :coupons, :except => [:destroy]
    resources :landing_pages
  end

  devise_for :admins, :controllers => { :registrations => "registrations", :sessions => "sessions" } do
    post "after_sign_in_path_for", :to => "sessions#after_sign_in_path_for", :as => "after_sign_in_path_for_session"
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations", :sessions => "sessions" } do
    get '/entrar' => 'sessions#new', :as => :new_user_session
    post '/entrar' => 'sessions#create', :as => :user_session
    delete '/logout' => 'sessions#destroy', :as => :destroy_user_session
    get '/users/auth/:provider' => 'omniauth_callbacks#passthru'
    post "after_sign_in_path_for", :to => "sessions#after_sign_in_path_for", :as => "after_sign_in_path_for_session"
  end
end

app/models/ecommerce/order.rb
# -*- encoding : utf-8 -*-
class Order < ActiveRecord::Base
  DEFAULT_QUANTITY = 1
  CONSTANT_NUMBER = 1782
  CONSTANT_FACTOR = 17

  STATUS = {
    "waiting_payment" => "Aguardando pagamento",
    "under_review" => "Em revisão",
    "canceled" => "Cancelado",
    "reversed" => "Estornado",
    "refunded" => "Reembolsado",
    "delivered" => "Entregue",
    "not_delivered" => "Não entregue",
    "picking" => "Separando",
    "authorized" => "Pagamento autorizado"
  }

  belongs_to :user
  has_many :variants, :through => :line_items
  has_many :line_items, :dependent => :destroy
  delegate :name, :to => :user, :prefix => true
  delegate :email, :to => :user, :prefix => true
  delegate :price, :to => :freight, :prefix => true, :allow_nil => true
  has_one :payment, :dependent => :destroy
  has_one :freight, :dependent => :destroy
  has_many :order_state_transitions, :dependent => :destroy
  has_many :order_events, :dependent => :destroy
  has_one :used_coupon, :dependent => :destroy
  after_create :generate_number
  after_create :generate_identification_code

  scope :with_payment, joins(:payment)

  state_machine :initial => :in_the_cart do

    store_audit_trail

    event :waiting_payment do
      transition :in_the_cart => :waiting_payment
    end

    event :authorized do
      transition :waiting_payment => :authorized
    end

    event :under_review do
      transition :authorized => :under_review
    end

    event :canceled do
      transition :waiting_payment => :canceled, :not_delivered => :canceled, :in_the_cart => :canceled
    end

    event :reversed do
      transition :under_review => :reversed
    end

    event :refunded do
      transition :under_review => :refunded
    end

    event :picking do
      transition :authorized => :picking, :under_review => :picking
    end

    event :delivering do
      transition :picking => :delivering
    end

    event :delivered do
      transition :delivering => :delivered
    end

    event :not_delivered do
      transition :delivering => :not_delivered
    end
  end

  def invalidate_coupon
    coupon = Coupon.lock("LOCK IN SHARE MODE").find_by_id(used_coupon.try(:coupon_id))
    if coupon
      coupon.decrement!(:remaining_amount, 1) unless coupon.unlimited?
    end
  end

  def clear_gift_in_line_items
    self.reload
    line_items.each {|item| item.update_attributes(:gift => false)}
  end

  def line_items_with_flagged_gift
    clear_gift_in_line_items
    flag_second_line_item_as_gift
    reload
    line_items.ordered_by_price
  end

  def flag_second_line_item_as_gift
    second_item = line_items.ordered_by_price[1]
    second_item.update_attributes(:gift => true) if second_item
  end

  def has_one_item_flagged_as_gift?
    line_items.select {|item| item.gift?}.size == 1
  end

  def status
    STATUS[state]
  end

  def remove_unavailable_items
    items = line_items.select {|item| !item.variant.available_for_quantity? item.quantity}
    size_items = items.size
    items.each {|item| item.destroy}
    size_items
  end

  def add_variant(variant, quantity = Order::DEFAULT_QUANTITY)
    quantity = quantity.to_i
    if variant.available_for_quantity?(quantity)
      current_item = line_items.select { |item| item.variant == variant }.first
      if current_item
        current_item.update_attributes(:quantity => quantity)
      else
        current_item =  LineItem.new(:order_id => id, :variant_id => variant.id, :quantity => quantity, :price => variant.price)
        line_items << current_item
      end
      current_item
    end
  end

  def remove_variant(variant)
    current_item = line_items.select { |item| item.variant == variant }.first
    current_item.destroy if current_item
  end

  def total_with_freight
    total + (freight_price || 0)
  end

  def line_items_total
    line_items.inject(0){|result, item| result + item.total_price}
  end

  def credits
    result = read_attribute :credits
    result.nil? ? 0 : result
  end

  def discount_from_coupon
    used_coupon ? used_coupon.value : 0
  end

  def discount_from_gift
    line_items.where(:gift => true).inject(0){|result, item| item.price}
  end

  def total
    result = line_items_total
    if result > 0
      result = result - credits
      result = result - discount_from_gift
      result = result - discount_from_coupon
    end
    result
  end

  def total_discount
    credits + discount_from_coupon + discount_from_gift
  end

  def generate_identification_code
    code = SecureRandom.hex(16)
    while Order.find_by_identification_code(code)
      code = SecureRandom.hex(16)
    end
    update_attributes(:identification_code => code)
  end

  def decrement_inventory_for_each_item
    ActiveRecord::Base.transaction do
      line_items.each do |item|
        variant = Variant.lock("LOCK IN SHARE MODE").find(item.variant.id)
        variant.decrement!(:inventory, item.quantity)
      end
    end
  end

  def increment_inventory_for_each_item
    ActiveRecord::Base.transaction do
      line_items.each do |item|
        variant = Variant.lock("LOCK IN SHARE MODE").find(item.variant.id)
        variant.increment!(:inventory, item.quantity)
      end
    end
  end

  def rollback_inventory
    increment_inventory_for_each_item
  end

  def installments
    payment.try(:payments) || 1
  end

  private

  def generate_number
    new_number = (id * CONSTANT_FACTOR) + CONSTANT_NUMBER
    update_attributes(:number => new_number)
  end
end

app/controllers/admin/orders_controller.rb
# -*- encoding : utf-8 -*-
class Admin::OrdersController < Admin::BaseController
  respond_to :html

  def index
    @search = Order.with_payment.search(params[:search])
    @orders = @search.relation.page(params[:page]).per_page(20).order('id DESC')
  end

  def show
    @order = Order.find(params[:id])
    @address = @order.freight.address
    respond_with :admin, @order, @address
  end
end

app/controllers/orders_controller.rb
# -*- encoding : utf-8 -*-
class OrdersController < ApplicationController
  layout "checkout"

  respond_to :html
  before_filter :authenticate_user!
  before_filter :load_user
  before_filter :load_resources

  def billet
  end

  def credit
  end

  def debit
  end

  private

  def load_resources
    @order = @user.orders.find_by_number!(params[:number])
    @payment = @order.payment
    @payment_response = @payment.payment_response
    @cart = Cart.new(@order)
    @promotion = ::ChristmasPromotion.new(@order)
  end
end

app/controllers/user/orders_controller.rb
# -*- encoding : utf-8 -*-
class User::OrdersController < ApplicationController
  layout "my_account"

  respond_to :html
  before_filter :authenticate_user!
  before_filter :load_user
  before_filter :load_order

  def index
    @orders = @user.orders.with_payment.order('created_at DESC').page(params[:page]).per_page(8)
  end

  def show
    @current_order = @user.orders.find_by_number(params[:number])
    @address = @current_order.freight.address
    @order_presenter = OrderStatus.new(@current_order)
  end

  private

  def load_user
    @user = current_user
  end
end

app/views/admin/orders/index.html.erb
<h2>Listing orders</h2>

<% content_for :sidebar do %>
  <div class="block">
    <h3>Filters</h3>

    <div class="content">
      <%= form_for([:admin, @search], :html => {:class => "form"}) do |f| %>
        <div class="group">
          <%= f.label :number_eq, "Number", :class => "label" %>
          <%= f.text_field :number_eq, :class => "text_field" %>
        </div>
        <div class="group">
          <%= f.label :user_first_name_contains, :class => "label" %>
          <%= f.text_field :user_first_name_contains, :class => "text_field" %>
        </div>
        <div class="group">
          <%= f.label :user_email_contains, :class => "label" %>
          <%= f.text_field :user_email_contains, :class => "text_field" %>
        </div>
        <div class="group">
          <%= f.label :created_at_gte, "Ordered from", :class => "label"  %>
          <%= f.date_select :created_at_gte, :include_blank => true %>
          <%= f.label :created_at_lte, "to", :class => "label" %>
          <%= f.date_select :created_at_lte, :include_blank => true %>
        </div>
        <div class="group">
          <%= f.label :state, "Status", :class => "label" %>
          <%= f.collection_select :state_eq, Order::STATUS.to_a, :first, :last, {:include_blank => true} %>
        </div>
        <div class="group">
          <%= f.label :state, "Payment Method", :class => "label" %>
          <%= f.select :payment_type_eq, {"Boleto Bancário" => "Billet", "Cartão de Crédito" => "CreditCard"} , {:include_blank => true} %>
        </div>

        <div class="group">
          <%= f.submit 'Search', :class => "button" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<div class="inner">
  <table class="table">
    <tr>
      <th><%= sort_link @search, :number %></th>
      <th><%= sort_link @search, :user_first_name, "Client" %></th>
      <th><%= sort_link @search, :user_email, "E-mail" %></th>
      <th><%= sort_link @search, :created_at, "Date" %></th>
      <th><%= sort_link @search, :state, "Status" %></th>
      <th><%= sort_link @search, :payment_type, "Payment Method" %></th>
      <th>Item count</th>
      <th>Products Total</th>
      <th>Freight Price</th>
      <th>Total</th>
      <th>x</th>
      <th></th>
    </tr>

  <% @orders.each do |order| %>
    <tr>
      <td><%= order.number %></td>
      <td><%= link_to order.user.name, admin_user_path(order.user) %></td>
      <td><%= link_to order.user.email, admin_user_path(order.user) %></td>
      <td><%= l order.created_at, :format => :short %></td>
      <td><%= order.status  %></td>
      <td><%= order.payment.human_to_s %></td>
      <td><%= order.line_items.count %></td>
      <td><%= number_to_currency(order.total) %></td>
      <td><%= number_to_currency(order.freight_price) %></td>
      <td><%= number_to_currency(order.total_with_freight) %></td>
      <td><%= order.installments %>x</td>
      <td><%= link_to 'Show', admin_order_path(order) %></td>
    </tr>
  <% end %>
  </table>

  <div class="actions-bar wat-cf">
    <div class="pagination">
      <%= will_paginate @orders %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<h2>Order <%= @order.number %></h2>
<div class="inner">
  <p>
    <b>Client:</b>
    <%= link_to "#{@order.user.name} - #{@order.user.email}", admin_user_path(@order.user) %>
  </p>

  <p>
    <b>Date:</b>
    <%= l @order.created_at, :format => :short %>
  </p>
  <p>
    <b>Status:</b>
    <%= @order.status %>
  </p>
  <p>
    <b>Payment method:</b>
    <%= @order.payment.human_to_s %> <%= "- #{@order.payment.bank}" if @order.payment.is_a? CreditCard %>
  </p>
  <p>
    <b>Products Total:</b>
    <%= number_to_currency(@order.total) %>
  </p>
  <p>
    <b>Freight Total:</b>
    <%= number_to_currency(@order.freight_price) %>
  </p>
  <p>
    <b>Total:</b>
    <%= number_to_currency(@order.total_with_freight) %>
  </p>
  <p>
    <b>Installments:</b>
    <%= @order.installments %>x
  </p>
  <p>
    <b>Estimated delivery:</b>
    <%= @order.freight.delivery_time %> work days
  </p>

  <div>
    <h3>Endereço de entrega</h1>
    <p><%= @address.identification %></p>
    <p><%= "#{@address.street}, #{@address.number} - #{@address.neighborhood}" %></p>
    <p><%= "#{@address.zip_code}" %></p>
    <p><%= "#{@address.city}, #{@address.state}" %></p>
  </div>
  
  <table class="table">
    <tr>
      <th></th>
      <th>SKU</th>
      <th>Product</th>
      <th>Quantity</th>
      <th>Unit Price</th>
      <th>Total</th>
    </tr>

  <% @order.line_items.each do |line_item| %>
    <tr>
      <td><%= image_tag(line_item.variant.thumb_picture) if line_item.variant.thumb_picture %></td>
      <td><%= link_to line_item.variant.sku, admin_product_path(line_item.variant.product) %></td>
      <td><%= link_to line_item.variant.name, admin_product_path(line_item.variant.product) %></td>
      <td><%= line_item.quantity  %></td>
      <td><%= number_to_currency(line_item.price) %></td>
      <td><%= number_to_currency(line_item.total_price) %></td>
    </tr>
  <% end %>
  </table>
</div>

<% content_for :secondary_navigation do %>
  <li><%= link_to 'Back', admin_orders_path %></li>
<% end %>