config/routes.rb
# -*- encoding : utf-8 -*-
Olook::Application.routes.draw do
  get "index/index"
  root :to => "home#index"

  match "/bem_vinda", :to => "pages#welcome", :as => "welcome"
  match "/sobre", :to => "pages#about", :as => "about"
  match "/termos", :to => "pages#terms", :as => "terms"
  match "/faq", :to => "pages#faq", :as => "faq"
  match "/privacidade", :to => "pages#privacy", :as => "privacy"
  match "/prazo-de-entrega", :to => "pages#delivery_time", :as => "delivery_time"
  match "/como-funciona", :to => "pages#how_to", :as => "how_to"
  match "/imprensa", :to => "pages#press_release", :as => "press_release"
  match "/lookbooks/lets-party", :to => "lookbooks#lets_party", :as => "lets_party"
  match "/lookbooks/palha", :to => "lookbooks#palha", :as => "palha"
  get   "/contato" => "pages#contact", :as => "contact"
  post  "/contato" => "pages#send_contact", :as => "send_contact"

  get '/pedido/:number/boleto', :to =>'orders#billet', :as => "order_billet"
  get '/pedido/:number/credito', :to =>'orders#credit', :as => "order_credit"
  get '/pedido/:number/debito', :to =>'orders#debit', :as => "order_debit"

  resource :criteo, :only => [:show], :path => 'criteo', :controller => :criteo

  resource :survey, :only => [:new, :create], :path => 'quiz', :controller => :survey
  resources :payments, :path => 'pagamento', :controller => :payments
  resources :credit_cards, :only => [:new, :create], :path => 'credito', :controller => :credit_cards
  resources :debits, :only => [:new, :create], :path => 'debito', :controller => :debits
  resources :billets, :only => [:new, :create], :path => 'boleto', :controller => :billets
  resources :addresses, :path => 'endereco', :controller => :addresses
  resource :cart, :only => [:show, :create, :update, :destroy, :update_status], :path => 'sacola', :controller => :cart do
    collection do
      put "update_bonus" => "cart#update_bonus", :as => "update_bonus"
      put "update_coupon" => "cart#update_coupon", :as => "update_coupon"
      put "update_quantity_product" => "cart#update_quantity_product", :as => "update_quantity_product"
    end
  end
  post "/assign_address", :to => "addresses#assign_address", :as => "assign_address"

  get "/produto/:id" => "product#show", :as => "product"
  get "membro/convite" => "members#invite", :as => 'member_invite'
  get "convite/(:invite_token)" => 'members#accept_invitation', :as => "accept_invitation"
  post "membro/convite_por_email" => 'members#invite_by_email', :as => 'member_invite_by_email'

  get "membro/importar_contatos" => "members#import_contacts", :as => 'member_import_contacts'
  post "membro/importar_contatos" => 'members#show_imported_contacts', :as => 'member_show_imported_contacts'

  post "membro/convidar_contatos" => "members#invite_imported_contacts", :as => 'member_invite_imported_contacts'
  get "membro/convidadas" => "members#invite_list", :as => 'member_invite_list'
  get "membro/vitrine", :to => "members#showroom", :as => "member_showroom"

  get '/conta/pedidos/:number', :controller =>'user/orders', :action => 'show' , :as => "user_order"

  get '/l/:page_url', :controller =>'landing_pages', :action => 'show' , :as => 'landing'

  namespace :user, :path => 'conta' do
    resources :users, :path => 'editar', :only => [:update]
    resources :addresses, :path => 'enderecos'
    resources :orders, :path => 'pedidos', :only => [:index]
    resources :credits, :path => 'creditos' do
      collection do
        post 'creditos/reenviar_convite/:id' => 'credits#resubmit_invite', :as => :resubmit_invite
        post 'creditos/reenviar_todos' => 'credits#resubmit_all_invites', :as => :resubmit_all_invites
      end
    end
  end

  namespace :admin do
    match "/", :to => "index#dashboard"

    resources :products do
      resources :pictures do
        collection do
          get  'multiple_pictures' => 'pictures#new_multiple_pictures', :as => 'new_multiple_pictures'
          post  'multiple_pictures' => 'pictures#create_multiple_pictures', :as => 'create_multiple_pictures'
        end
      end
      resources :details
      resources :variants
      member do
        post 'add_related' => "products#add_related", :as => "add_related"
        delete 'remove_related/:related_product_id' => "products#remove_related", :as => "remove_related"
      end
    end

    resources :users, :except => [:create, :new, :destroy] do
      collection do
        get 'statistics' => 'users#statistics', :as => 'statistics'
        get 'export' => 'users#export', :as => 'export'
      end
    end

    resources :utilities do
      collection do
        post 'restart_resque_workers' => "utilities#restart_resque_workers", :as => "restart_resque_workers"
        post 'invalidates_cdn_content' => "utilities#invalidates_cdn_content", :as => "invalidates_cdn_content"
      end
    end
    resources :shipping_services
    resources :collections
    resources :orders
    resources :coupons, :except => [:destroy]
    resources :landing_pages
  end

  devise_for :admins, :controllers => { :registrations => "registrations", :sessions => "sessions" } do
    post "after_sign_in_path_for", :to => "sessions#after_sign_in_path_for", :as => "after_sign_in_path_for_session"
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations", :sessions => "sessions" } do
    get '/entrar' => 'sessions#new', :as => :new_user_session
    post '/entrar' => 'sessions#create', :as => :user_session
    delete '/logout' => 'sessions#destroy', :as => :destroy_user_session
    get '/users/auth/:provider' => 'omniauth_callbacks#passthru'
    post "after_sign_in_path_for", :to => "sessions#after_sign_in_path_for", :as => "after_sign_in_path_for_session"
  end
end

app/models/ecommerce/payment.rb
# -*- encoding : utf-8 -*-
class Payment < ActiveRecord::Base
  has_paper_trail
  MINIMUM_VALUE = 5.0
  SUCCESSFUL_STATUS = 'Sucesso'
  FAILURE_STATUS = 'Falha'
  CANCELED_STATUS = 'Cancelado'
  REASON = 'Pagamento'
  RECEIPT = 'AVista'
  STATUS = {
    "1" => :authorized,
    "2" => :started,
    "3" => :billet_printed,
    "4" => :completed,
    "5" => :canceled,
    "6" => :under_analysis,
    "7" => :reversed,
    "8" => :under_review,
    "9" => :refunded
  }

  RESPONSE_STATUS = {
    "Autorizado" => "Autorizado",
    "Iniciado" => "Iniciado",
    "BoletoImpresso" => "Boleto Impresso",
    "Completo" => "Completo",
    "Cancelado" => "Cancelado",
    "EmAnalise" => "Em Análise",
    "Estornado" => "Estornado",
    "EmRevisao" => "Em Revisão",
    "Reembolsado" => "Reembolsado"
  }

  attr_accessor :receipt, :user_identification

  belongs_to :order
  has_one :payment_response, :dependent => :destroy

  def credit_card?
    (self.type == "CreditCard") ? true : false
  end

  def expired_and_waiting_payment?
    (self.expired? && self.order.state == "waiting_payment") ? true : false
  end

  def expired?
    Time.now > self.payment_expiration_date if self.payment_expiration_date
  end

  def set_payment_expiration_date
    update_attributes(:payment_expiration_date => build_payment_expiration_date)
  end

  def save_with(payment_url, order)
    self.url, self.order = payment_url, order
    save
  end

  def set_state(status)
    event = STATUS[status]
    send(event) if event
  end

  def refund_order
    order.refunded
  end

  def review_order
    order.under_review
  end

  def cancel_order
    order.canceled
  end

  def authorize_order
    order.authorized
  end
end

app/controllers/payments_controller.rb
# -*- encoding : utf-8 -*-
class PaymentsController < ApplicationController
  layout "checkout"

  include Checkout
  respond_to :html
  before_filter :authenticate_user!, :only => [:index]
  before_filter :load_user, :except => [:create]
  skip_before_filter :check_order, :only => [:show, :create]
  before_filter :check_freight, :only => [:index]
  before_filter :build_cart, :only => [:index]
  before_filter :load_promotion
  protect_from_forgery :except => :create

  def index
  end

  def show
    @payment = @user.payments.find(params[:id])
    @cart = Cart.new(@payment.order)
  end

  def create
    identification_code = params["id_transacao"]
    logger.error identification_code
    order = Order.find_by_identification_code(identification_code)
    if order
      if update_order(order)
        render :nothing => true, :status => 200
      else
        msg = "Erro ao mudar status do pagamento"
        Airbrake.notify(:error_class => "Payment", :error_message => msg, :parameters => params)
        logger.error(msg)
        render :nothing => true, :status => 500
      end
    else
      msg = "Order não encontrada"
      Airbrake.notify(:error_class => "Order", :error_message => msg, :parameters => params)
      logger.error(msg)
      render :nothing => true, :status => 500
    end
  end

  private

  def update_order(order)
    order.payment.update_attributes(:gateway_code => params["cod_moip"], :gateway_type => params["tipo_pagamento"], :gateway_status => params["status_pagamento"])
    order.payment.set_state(params["status_pagamento"])
  end
end

app/views/shared/payments/_info_address.html.erb
<div class="item">
  <h1>Endereço de entrega <%= link_to "alterar", addresses_path if @order.payment.nil? %></h1>
  <p><strong><%= order.freight.address.identification %></strong></p>
  <p><%= "#{order.freight.address.street}, #{order.freight.address.number}" %><%= order.freight.address.complement? ? ", #{order.freight.address.complement}" : "" %></p>
  <p><%= "#{order.freight.address.neighborhood} - #{order.freight.address.zip_code}" %></p>
  <p><%= "#{order.freight.address.city}, #{order.freight.address.state}" %></p>
</div>

app/views/shared/payments/_info_payment.html.erb
<div class="item">
  <h1>Pagamento</h1>
  <table cellpadding="0" cellspacing="0">
    <tbody>
      <tr>
        <td><%= @order.payment.human_to_s %></td>
        <td class="value"><%= number_to_currency(@order.total_with_freight) %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/shared/payments/_info_sidebar.html.erb
<div id="request_info">
  <%= yield :checkout_sidebar %>
  <div class="item">
    <h1>Meu Pedido <%= link_to "alterar", cart_path if @order.payment.nil? %></h1>
    <table cellpadding="0" cellspacing="0">
      <tfoot>
        <tr>
          <td>Total:</td>
          <td class="value"><%= number_to_currency(cart.total) %></td>
        </tr>
      </tfoot>
      <tbody>
        <tr>
          <td>Sub-total:</td>
          <td class="value"><%= number_to_currency(cart.subtotal)  %></td>
        </tr>
        <tr>
          <td>Crédito</td>
          <td class="value credit">- <%= number_to_currency(cart.credits_discount) %></td>
        </tr>
        <% if @order.used_coupon %>
          <tr>
            <td>Cupom desconto</td>
            <td class="value credit">- <%= number_to_currency(cart.coupon_discount) %></td>
          </tr>
        <% end %>
        <tr>
          <td>Frete</td>
          <td class="value">+ <%= number_to_currency(cart.freight_price) %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/shared/payments/_payment_methods.html.erb
<ul class="payment_methods">
  <li class="credit_card">
    <p>Cartão de crédito</p>
    <%= link_to "Cartão de Crédito", new_credit_card_path, :class => selected_if_current(["credit_cards#new"]) %>
  </li>
  <li class="debit">
    <p>Transferência bancária</p>
    <%= link_to "Débito Bancário", new_debit_path, :class => selected_if_current(["debits#new"]) %>
  </li>
  <li class="billet">
    <p>Boleto</p>
    <%= link_to "Boleto Bancário", new_billet_path, :class => selected_if_current(["billets#new"]) %>
  </li>
</ul>