config/routes.rb
# -*- encoding : utf-8 -*-
Olook::Application.routes.draw do
  get "index/index"
  root :to => "home#index"

  match "/bem_vinda", :to => "pages#welcome", :as => "welcome"
  match "/sobre", :to => "pages#about", :as => "about"
  match "/termos", :to => "pages#terms", :as => "terms"
  match "/faq", :to => "pages#faq", :as => "faq"
  match "/privacidade", :to => "pages#privacy", :as => "privacy"
  match "/prazo-de-entrega", :to => "pages#delivery_time", :as => "delivery_time"
  match "/como-funciona", :to => "pages#how_to", :as => "how_to"
  match "/imprensa", :to => "pages#press_release", :as => "press_release"
  match "/lookbooks/lets-party", :to => "lookbooks#lets_party", :as => "lets_party"
  match "/lookbooks/palha", :to => "lookbooks#palha", :as => "palha"
  get   "/contato" => "pages#contact", :as => "contact"
  post  "/contato" => "pages#send_contact", :as => "send_contact"

  get '/pedido/:number/boleto', :to =>'orders#billet', :as => "order_billet"
  get '/pedido/:number/credito', :to =>'orders#credit', :as => "order_credit"
  get '/pedido/:number/debito', :to =>'orders#debit', :as => "order_debit"

  resource :criteo, :only => [:show], :path => 'criteo', :controller => :criteo

  resource :survey, :only => [:new, :create], :path => 'quiz', :controller => :survey
  resources :payments, :path => 'pagamento', :controller => :payments
  resources :credit_cards, :only => [:new, :create], :path => 'credito', :controller => :credit_cards
  resources :debits, :only => [:new, :create], :path => 'debito', :controller => :debits
  resources :billets, :only => [:new, :create], :path => 'boleto', :controller => :billets
  resources :addresses, :path => 'endereco', :controller => :addresses
  resource :cart, :only => [:show, :create, :update, :destroy, :update_status], :path => 'sacola', :controller => :cart do
    collection do
      put "update_bonus" => "cart#update_bonus", :as => "update_bonus"
      put "update_coupon" => "cart#update_coupon", :as => "update_coupon"
      put "update_quantity_product" => "cart#update_quantity_product", :as => "update_quantity_product"
    end
  end
  post "/assign_address", :to => "addresses#assign_address", :as => "assign_address"

  get "/produto/:id" => "product#show", :as => "product"
  get "membro/convite" => "members#invite", :as => 'member_invite'
  get "convite/(:invite_token)" => 'members#accept_invitation', :as => "accept_invitation"
  post "membro/convite_por_email" => 'members#invite_by_email', :as => 'member_invite_by_email'

  get "membro/importar_contatos" => "members#import_contacts", :as => 'member_import_contacts'
  post "membro/importar_contatos" => 'members#show_imported_contacts', :as => 'member_show_imported_contacts'

  post "membro/convidar_contatos" => "members#invite_imported_contacts", :as => 'member_invite_imported_contacts'
  get "membro/convidadas" => "members#invite_list", :as => 'member_invite_list'
  get "membro/vitrine", :to => "members#showroom", :as => "member_showroom"

  get '/conta/pedidos/:number', :controller =>'user/orders', :action => 'show' , :as => "user_order"

  get '/l/:page_url', :controller =>'landing_pages', :action => 'show' , :as => 'landing'

  namespace :user, :path => 'conta' do
    resources :users, :path => 'editar', :only => [:update]
    resources :addresses, :path => 'enderecos'
    resources :orders, :path => 'pedidos', :only => [:index]
    resources :credits, :path => 'creditos' do
      collection do
        post 'creditos/reenviar_convite/:id' => 'credits#resubmit_invite', :as => :resubmit_invite
        post 'creditos/reenviar_todos' => 'credits#resubmit_all_invites', :as => :resubmit_all_invites
      end
    end
  end

  namespace :admin do
    match "/", :to => "index#dashboard"

    resources :products do
      resources :pictures do
        collection do
          get  'multiple_pictures' => 'pictures#new_multiple_pictures', :as => 'new_multiple_pictures'
          post  'multiple_pictures' => 'pictures#create_multiple_pictures', :as => 'create_multiple_pictures'
        end
      end
      resources :details
      resources :variants
      member do
        post 'add_related' => "products#add_related", :as => "add_related"
        delete 'remove_related/:related_product_id' => "products#remove_related", :as => "remove_related"
      end
    end

    resources :users, :except => [:create, :new, :destroy] do
      collection do
        get 'statistics' => 'users#statistics', :as => 'statistics'
        get 'export' => 'users#export', :as => 'export'
      end
    end

    resources :utilities do
      collection do
        post 'restart_resque_workers' => "utilities#restart_resque_workers", :as => "restart_resque_workers"
        post 'invalidates_cdn_content' => "utilities#invalidates_cdn_content", :as => "invalidates_cdn_content"
      end
    end
    resources :shipping_services
    resources :collections
    resources :orders
    resources :coupons, :except => [:destroy]
    resources :landing_pages
  end

  devise_for :admins, :controllers => { :registrations => "registrations", :sessions => "sessions" } do
    post "after_sign_in_path_for", :to => "sessions#after_sign_in_path_for", :as => "after_sign_in_path_for_session"
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations", :sessions => "sessions" } do
    get '/entrar' => 'sessions#new', :as => :new_user_session
    post '/entrar' => 'sessions#create', :as => :user_session
    delete '/logout' => 'sessions#destroy', :as => :destroy_user_session
    get '/users/auth/:provider' => 'omniauth_callbacks#passthru'
    post "after_sign_in_path_for", :to => "sessions#after_sign_in_path_for", :as => "after_sign_in_path_for_session"
  end
end

app/models/collection.rb
# -*- encoding : utf-8 -*-
class Collection < ActiveRecord::Base
  has_many :products

  validates :start_date, :presence => true
  validates :end_date, :presence => true
  validate :any_active_collections?

  def self.for_date(date)
    Collection.where( '(:date >= start_date) AND (:date <= end_date)',
                      :date => date).first
  end

  def self.current
    self.for_date(Date.today)
  end

  def self.active
    Collection.where(:is_active => true).first
  end

  def any_active_collections?
    collections = Collection.where(:is_active => true).all
    if self.is_active
      if collections.any? && !is_current_active?(collections)
        errors.add(:is_active, ": only one collection can be active at the same time. Deactivate an existing one before you proceed")
      end
    end
  end

  private
  def is_current_active?(collections)
    collections.collect! {|col| col.id}
    if collections.include?(self.id)
      true
    end
  end

end

app/controllers/admin/collections_controller.rb
# -*- encoding : utf-8 -*-
class Admin::CollectionsController < Admin::BaseController
  respond_to :html

  def index
    @collections = Collection.all
    respond_with :admin, @collections
  end

  def show
    @collection = Collection.find(params[:id])
    respond_with :admin, @collection
  end

  def new
    @collection = Collection.new
    respond_with :admin, @collection
  end

  def edit
    @collection = Collection.find(params[:id])
    respond_with :admin, @collection
  end

  def create
    @collection = Collection.new(params[:collection])
      if @collection.save
        flash[:notice] = 'Collection was successfully created.'
      end
    respond_with :admin, @collection
  end

  def update
    @collection = Collection.find(params[:id])
      if @collection.update_attributes(params[:collection])
        flash[:notice] = 'Collection was successfully updated.'
      end
    respond_with :admin, @collection
  end

  def destroy
    @collection = Collection.find(params[:id])
    @collection.destroy
    respond_with :admin, @collection
  end
end

app/views/admin/collections/_form.html.erb
<%= form_for([:admin, @collection], :html => { :multipart => true }) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br />
    <%= f.check_box :is_active %>
  </div>  


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/collections/_products.html.erb
<h2>Products</h2>
<div class="inner">
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Model number</th>
      <th>Category</th>
      <th>Color</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= image_tag product.pictures.first.try(:image_url, :thumb) %></td>
      <td><%= product.model_number %></td>
      <td><%= product.category_humanize %></td>
      <td><%= product.color_name %></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/admin/collections/edit.html.erb
<h2>Editing collection</h2>

<div class="inner">
  <%= render 'form' %>
</div>

<% content_for :secondary_navigation do %>
  <li><%= link_to 'Show', admin_collection_path(@collection) %></li>
  <li><%= link_to 'Back', admin_collections_path %></li>
<% end %>

app/views/admin/collections/index.html.erb
<h2>Listing collections</h2>

<div class="inner">
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Active</th>
      <th>Product Count</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @collections.each do |collection| %>
    <tr>
      <td><%= collection.name %></td>
      <td><%= l collection.start_date %></td>
      <td><%= l collection.end_date %></td>
      <td><%= collection.is_active %></td>
      <td><%= collection.products.count %></td>
      <td><%= link_to 'Show', admin_collection_path(collection) %></td>
      <td><%= link_to 'Edit', edit_admin_collection_path(collection) %></td>
      <td><%= link_to 'Destroy', admin_collection_path(collection), confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  </table>

  <br />
</div>

<% content_for :secondary_navigation do %>
  <li><%= link_to 'New Collection', new_admin_collection_path %></li>
<% end %>

app/views/admin/collections/new.html.erb
<h2>New collection</h2>

<div class="inner">
  <%= render 'form' %>
</div>

<% content_for :secondary_navigation do %>
  <li><%= link_to 'Back', admin_collections_path %></li>
<% end %>

app/views/admin/collections/show.html.erb
<h2>Collection</h2>
<div class="inner">
  <p>
    <b>Name:</b>
    <%= @collection.name %>
  </p>

  <p>
    <b>Start date:</b>
    <%= l @collection.start_date %>
  </p>
  <p>
    <b>End date:</b>
    <%= l @collection.start_date %>
  </p>

  <%= render :partial => 'products', :locals => {:products => @collection.products} %>
  
</div>

<% content_for :secondary_navigation do %>
  <li><%= link_to 'Edit', edit_admin_collection_path(@collection) %></li>
  <li><%= link_to 'Back', admin_collections_path %></li>
<% end %>